{
    "openapi": "3.0.3",
    "info": {
        "title": "Mobile API",
        "description": "Membuat API untuk tugas besar Mobile Development",
        "version": "1.0.0",
        "contact": {
            "name": "Kelompok 7"
        }
    },
    "servers": [
        {
            "description": "Tugas Besar Mobile Development",
            "url": "http://localhost:8000/api/"
        }
    ],
    "paths": {
        "/transaction": {
            "get": {
                "tags": ["Transaction"],
                "summary": "Get All Transaction",
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "Bearer token",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Get Transaction Details",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "data": {
                                                    "type": "object",
                                                    "properties": {
                                                        "id": {
                                                            "type": "string"
                                                        },
                                                        "wallet": {
                                                            "type": "string"
                                                        },
                                                        "category": {
                                                            "type": "string"
                                                        },
                                                        "amount": {
                                                            "type": "number"
                                                        },
                                                        "description": {
                                                            "type": "string"
                                                        },
                                                        "transaction_date": {
                                                            "type": "string"
                                                        },
                                                        "user": {
                                                            "type": "object",
                                                            "properties": {
                                                                "fullname": {
                                                                    "type": "string"
                                                                },
                                                                "phone_number": {
                                                                    "type": "string"
                                                                },
                                                                "email": {
                                                                    "type": "string"
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Success": {
                                        "description": "Success Get Transaction Details",
                                        "value": {
                                            "data": {
                                                "status": "success",
                                                "code": 200,
                                                "message": "Get Transaction Details Successfully",
                                                "data": [
                                                    {
                                                        "id": 1,
                                                        "wallet": "Cash Wallet",
                                                        "category": "Makanan",
                                                        "amount": 50000,
                                                        "description": "KFC",
                                                        "transaction_date": "22 November 2024",
                                                        "user": {
                                                            "fullname": "John Doe",
                                                            "phone_number": "08123456789",
                                                            "email": "2IgMh@example.com"
                                                        }
                                                    },
                                                    {
                                                        "id": 2,
                                                        "wallet": "Cash Wallet",
                                                        "category": "Makanan",
                                                        "amount": 15000,
                                                        "description": "Nasi Padang",
                                                        "transaction_date": "22 November 2024",
                                                        "user": {
                                                            "fullname": "John Doe",
                                                            "phone_number": "08123456789",
                                                            "email": "2IgMh@example.com"
                                                        }
                                                    }
                                                    
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "errors": {
                                                    "type": "object"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "status": "unauthorized",
                                            "code": 401,
                                            "message": "Unauthorized",
                                            "errors": {
                                                "message": "Unauthorized"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Internal Server Error",
                                        "value": {
                                            "status": "error",
                                            "code": 500,
                                            "message": "Internal Server Error",
                                            "errors": {
                                                "message": "Internal Server Error"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["Transaction"],
                "summary": "Create Transaction",
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "Bearer token",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "wallet_id": {
                                        "type": "integer"
                                    },
                                    "category_id": {
                                        "type": "integer"
                                    },
                                    "amount": {
                                        "type": "number"
                                    },
                                    "description": {
                                        "type": "string"
                                    },
                                    "transaction_date":{
                                        "type": "string"
                                    }
                                }
                            },
                            "examples": {
                                "Wallet": {
                                    "description": "Example create Transaction",
                                    "value": {
                                        "wallet_id": 1,
                                        "category_id": 2,
                                        "amount": 100000,
                                        "description": "Work",
                                        "transaction_date": "20 November 2024"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success create new Transaction",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "data": {
                                                    "type": "object",
                                                    "properties": {
                                                        "id": {
                                                            "type": "string"
                                                        },
                                                        "wallet": {
                                                            "type": "string"
                                                        },
                                                        "category": {
                                                            "type": "string"
                                                        },
                                                        "amount": {
                                                            "type": "number"
                                                        },
                                                        "description": {
                                                            "type": "string"
                                                        },
                                                        "transaction_date": {
                                                            "type": "string"
                                                        },
                                                        "user": {
                                                            "type": "object",
                                                            "properties": {
                                                                "fullname": {
                                                                    "type": "string"
                                                                },
                                                                "phone_number": {
                                                                    "type": "string"
                                                                },
                                                                "email": {
                                                                    "type": "string"
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Success": {
                                        "description": "Success create Transaction",
                                        "value": {
                                            "status": "success",
                                            "code": 200,
                                            "message": "Create Transaction Successfully",
                                            "data": {
                                                "id": 3,
                                                "wallet": "Cash Wallet",
                                                "category": "Gaji",
                                                "amount": 100000,
                                                "description": "Work",
                                                "transaction_date": "20 November 2024",
                                                "user": {
                                                    "fullname": "John Doe",
                                                    "phone_number": "08123456789",
                                                    "email": "2IgMh@example.com"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "errors": {
                                                    "type": "object"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "status": "unauthorized",
                                            "code": 401,
                                            "message": "Unauthorized",
                                            "errors": {
                                                "message": "Unauthorized"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Errors": {
                                        "description": "Invalid input data",
                                        "value": {
                                            "status": "bad request",
                                            "code": 400,
                                            "message": "Invalid input data",
                                            "errors": {
                                                "wallet_id": "Wallet ID is required",
                                                "category_id": "Category ID is required",
                                                "amount": "Amount is required",
                                                "transaction_date": "Transaction Date is required"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Internal Server Error",
                                        "value": {
                                            "status": "error",
                                            "code": 500,
                                            "message": "Internal Server Error",
                                            "errors": {
                                                "message": "Internal Server Error"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/transaction/{id}": {
            "get": {
                "tags": ["Transaction"],
                "summary": "Get Transaction by ID",
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID of the transaction",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "Bearer token",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success get transaction",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "string"
                                                },
                                                "wallet": {
                                                    "type": "string"
                                                },
                                                "category": {
                                                    "type": "string"
                                                },
                                                "amount": {
                                                    "type": "integer"
                                                },
                                                "description": {
                                                    "type": "string"
                                                },
                                                "transaction_date":{
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Success": {
                                        "description": "Success get transaction",
                                        "value": {
                                            "status": "success",
                                            "code": 200,
                                            "message": "Success get transaction",
                                            "data": {
                                                "id": 2,
                                                "user_id": 0,
                                                "wallet_id": 2,
                                                "category_id": 1,
                                                "amount": 100000,
                                                "description": "Convenience Store"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Not Found",
                                        "value": {
                                            "status": "not found",
                                            "code": 404,
                                            "message": "Transaction not found",
                                            "errors": {
                                                "message": "Transaction not found"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Internal Server Error",
                                        "value": {
                                            "status": "error",
                                            "code": 500,
                                            "message": "Internal Server Error",
                                            "errors": {
                                                "message": "Internal Server Error"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": ["Transaction"],
                "summary": "Transaction Wallet",
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID of the transaction",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "Bearer token",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "wallet_id": { "type": "integer" },
                                    "category_id": { "type": "integer" },
                                    "amount": { "type": "number" },
                                    "description": { "type": "string" },
                                    "transaction_date": { "type": "string"}
                                }
                            },
                            "examples": {
                                "Wallet": {
                                    "summary": "Example Transaction update",
                                    "value": {
                                        "wallet_id": 1,
                                        "category_id": 1,
                                        "amount": 100000,
                                        "description": "Convenience Store",
                                        "transaction_date": "19 November 2024"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success Update Transaction",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Errors": {
                                        "description": "Input data is not valid",
                                        "value": {
                                            "status": "bad request",
                                            "code": 400,
                                            "message": "Input data is not valid",
                                            "errors": {
                                                "wallet_id": "Wallet ID field is required",
                                                "category_id": "Category ID field is required",
                                                "amount": "Amount field is required",
                                                "transaction_date": "Transaction Date field is required"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "errors": {
                                                    "type": "object"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "status": "unauthorized",
                                            "code": 401,
                                            "message": "Unauthorized",
                                            "errors": {
                                                "message": "Unauthorized"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": ["Transaction"],
                "summary": "Delete Transaction",
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID of the Transaction",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "Bearer token",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Delete Transaction",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Success": {
                                        "description": "Success Delete Transaction",
                                        "value": {
                                            "status": "success",
                                            "code": 200,
                                            "message": "Delete Transaction Successfully"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "errors": {
                                                    "type": "object"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "status": "unauthorized",
                                            "code": 401,
                                            "message": "Unauthorized",
                                            "errors": {
                                                "message": "Unauthorized"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Internal Server Error",
                                        "value": {
                                            "status": "error",
                                            "code": 500,
                                            "message": "Internal Server Error",
                                            "errors": {
                                                "message": "Internal Server Error"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "UserAuth": {
                "description": "Authentication for API",
                "type": "apiKey",
                "in": "header",
                "name": "Authorization"
            }
        }
    }
}
