{
    "openapi": "3.0.3",
    "info": {
        "title": "Mobile API",
        "description": "Membuat API untuk tugas besar Mobile Development",
        "version": "1.0.0",
        "contact": {
            "name": "Kelompok 7"
        }
    },
    "servers": [
        {
            "description": "Tugas Besar Mobile Development",
            "url": "http://localhost:8000/api/"
        }
    ],
    "paths": {
        "/wallet": {
            "get": {
                "tags": ["Wallet"],
                "summary": "Get All Wallet",
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "Bearer token",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Get Wallet Details",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "data": {
                                                    "type": "object",
                                                    "properties": {
                                                        "id": {
                                                            "type": "string"
                                                        },
                                                        "user_id": {
                                                            "type": "integer"
                                                        },
                                                        "name": {
                                                            "type": "string"
                                                        },
                                                        "balance": {
                                                            "type": "number"
                                                        },
                                                        "is_active": {
                                                            "type": "boolean"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Success": {
                                        "description": "Success Get Wallet Details",
                                        "value": {
                                            "data": {
                                                "status": "success",
                                                "code": 200,
                                                "message": "Get Wallet Details Successfully",
                                                "data": [
                                                    {
                                                        "id": 1,
                                                        "user_id": 0,
                                                        "name": "Cash Wallet",
                                                        "balance": 50000,
                                                        "is_active": 0
                                                    },
                                                    {
                                                        "id": 2,
                                                        "user_id": 0,
                                                        "name": "Credit Card Wallet",
                                                        "balance": 100000,
                                                        "is_active": 1
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "errors": {
                                                    "type": "object"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "status": "unauthorized",
                                            "code": 401,
                                            "message": "Unauthorized",
                                            "errors": {
                                                "message": "Unauthorized"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Internal Server Error",
                                        "value": {
                                            "status": "error",
                                            "code": 500,
                                            "message": "Internal Server Error",
                                            "errors": {
                                                "message": "Internal Server Error"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["Wallet"],
                "summary": "Create Wallet",
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "Authorization",
                        "in": "header",
                        "description": "Bearer token",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "string"
                                    },
                                    "user_id": {
                                        "type": "integer"
                                    },
                                    "name": {
                                        "type": "string"
                                    },
                                    "balance": {
                                        "type": "number"
                                    },
                                    "is_active": {
                                        "type": "boolean"
                                    }
                                }
                            },
                            "examples": {
                                "Wallet": {
                                    "description": "Example create Wallet",
                                    "value": {
                                        "id": 3,
                                        "user_id": 1,
                                        "name": "Bank Wallet",
                                        "balance": 100000,
                                        "is_active": false
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success create wallet",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "data": {
                                                    "type": "object",
                                                    "properties": {
                                                        "id": {
                                                            "type": "string"
                                                        },
                                                        "user_id": {
                                                            "type": "integer"
                                                        },
                                                        "name": {
                                                            "type": "string"
                                                        },
                                                        "balance": {
                                                            "type": "number"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Success": {
                                        "description": "Success create wallet",
                                        "value": {
                                            "status": "success",
                                            "code": 200,
                                            "message": "Create Wallet Successfully",
                                            "data": {
                                                "id": "3",
                                                "user_id": 1,
                                                "name": "Credit Card Wallet",
                                                "balance": 1000.00,
                                                "is_active":true
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "errors": {
                                                    "type": "object"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "status": "unauthorized",
                                            "code": 401,
                                            "message": "Unauthorized",
                                            "errors": {
                                                "message": "Unauthorized"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Errors": {
                                        "description": "Invalid input data",
                                        "value": {
                                            "status": "bad request",
                                            "code": 400,
                                            "message": "Invalid input data",
                                            "errors": {
                                                "user_id": "User ID is required",
                                                "balance": "Balance is required",
                                                "is_active": "Status is required",
                                                "name": "Name is required"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Internal Server Error",
                                        "value": {
                                            "status": "error",
                                            "code": 500,
                                            "message": "Internal Server Error",
                                            "errors": {
                                                "message": "Internal Server Error"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/wallet/{id}": {
            "get": {
                "tags": ["Wallet"],
                "summary": "Get Wallet by ID",
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID of the wallet",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success get category",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "id": {
                                                    "type": "string"
                                                },
                                                "user_id": {
                                                    "type": "string"
                                                },
                                                "name": {
                                                    "type": "string"
                                                },
                                                "balance": {
                                                    "type": "integer"
                                                },
                                                "is_active": {
                                                    "type": "boolean"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Success": {
                                        "description": "Success get wallet",
                                        "value": {
                                            "status": "success",
                                            "code": 200,
                                            "message": "Success get wallet",
                                            "data": {
                                                "id": 2,
                                                "name": "Credit Card Wallet",
                                                "balance": 1000000,
                                                "is_active": 0
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Not Found",
                                        "value": {
                                            "status": "not found",
                                            "code": 404,
                                            "message": "Wallet not found",
                                            "errors": {
                                                "message": "Wallet not found"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Internal Server Error",
                                        "value": {
                                            "status": "error",
                                            "code": 500,
                                            "message": "Internal Server Error",
                                            "errors": {
                                                "message": "Internal Server Error"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": ["Wallet"],
                "summary": "Update Wallet",
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID of the wallet",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": { "type": "string" },
                                    "balance": { "type": "number" },
                                    "is_active": { "type": "boolean" }
                                }
                            },
                            "examples": {
                                "Wallet": {
                                    "summary": "Example Wallet update",
                                    "value": {
                                        "user_id": 1,
                                        "name": "New Wallet Name",
                                        "balance": 500.00,
                                        "is_active": true
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success Update Wallet",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Errors": {
                                        "description": "Input data is not valid",
                                        "value": {
                                            "status": "bad request",
                                            "code": 400,
                                            "message": "Input data is not valid",
                                            "errors": {
                                                "name": "Name field is required",
                                                "balance": "Balance field is required"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "errors": {
                                                    "type": "object"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "status": "unauthorized",
                                            "code": 401,
                                            "message": "Unauthorized",
                                            "errors": {
                                                "message": "Unauthorized"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": ["Wallet"],
                "summary": "Delete Wallet",
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID of the wallet",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Delete Wallet",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Success": {
                                        "description": "Success Delete Wallet",
                                        "value": {
                                            "status": "success",
                                            "code": 200,
                                            "message": "Delete Wallet Successfully"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "errors": {
                                                    "type": "object"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "status": "unauthorized",
                                            "code": 401,
                                            "message": "Unauthorized",
                                            "errors": {
                                                "message": "Unauthorized"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Internal Server Error",
                                        "value": {
                                            "status": "error",
                                            "code": 500,
                                            "message": "Internal Server Error",
                                            "errors": {
                                                "message": "Internal Server Error"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/wallet/switch/{id}": {
            "put": {
                "tags": ["Wallet"],
                "summary": "Switch Wallet Active Status",
                "security": [
                    {
                        "UserAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "ID of the wallet",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Switch Wallet",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "string"
                                        },
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        },
                                        "errors": {
                                            "type": "object"
                                        }
                                    }
                                },
                                "examples": {
                                    "Errors": {
                                        "description": "Input data is not valid",
                                        "value": {
                                            "status": "bad request",
                                            "code": 400,
                                            "message": "Input data is not valid",
                                            "errors": {
                                                "id": "Wallet ID is required"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "status": {
                                                    "type": "string"
                                                },
                                                "code": {
                                                    "type": "integer"
                                                },
                                                "message": {
                                                    "type": "string"
                                                },
                                                "errors": {
                                                    "type": "object"
                                                }
                                            }
                                        }
                                    }
                                },
                                "examples": {
                                    "Error": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "status": "unauthorized",
                                            "code": 401,
                                            "message": "Unauthorized",
                                            "errors": {
                                                "message": "Unauthorized"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "UserAuth": {
                "description": "Authentication for API",
                "type": "apiKey",
                "in": "header",
                "name": "Authorization"
            }
        }
    }
}
